// List from https://gist.github.com/sebleier/554280
export const STOPWORDS = new Set([
  'i',
  'me',
  'my',
  'myself',
  'we',
  'our',
  'ours',
  'ourselves',
  'you',
  'your',
  'yours',
  'yourself',
  'yourselves',
  'he',
  'him',
  'his',
  'himself',
  'she',
  'her',
  'hers',
  'herself',
  'it',
  'its',
  'itself',
  'they',
  'them',
  'their',
  'theirs',
  'themselves',
  'what',
  'which',
  'who',
  'whom',
  'this',
  'that',
  'these',
  'those',
  'am',
  'is',
  'are',
  'was',
  'were',
  'be',
  'been',
  'being',
  'have',
  'has',
  'had',
  'having',
  'do',
  'does',
  'did',
  'doing',
  'a',
  'an',
  'the',
  'and',
  'but',
  'if',
  'or',
  'because',
  'as',
  'until',
  'while',
  'of',
  'at',
  'by',
  'for',
  'with',
  'about',
  'against',
  'between',
  'into',
  'through',
  'during',
  'before',
  'after',
  'above',
  'below',
  'to',
  'from',
  'up',
  'down',
  'in',
  'out',
  'on',
  'off',
  'over',
  'under',
  'again',
  'further',
  'then',
  'once',
  'here',
  'there',
  'when',
  'where',
  'why',
  'how',
  'all',
  'any',
  'both',
  'each',
  'few',
  'more',
  'most',
  'other',
  'some',
  'such',
  'no',
  'nor',
  'not',
  'only',
  'own',
  'same',
  'so',
  'than',
  'too',
  'very',
  's',
  't',
  'can',
  'will',
  'just',
  'don',
  'should',
  'now',
])

export const JURISDICTION_ALIASES = {
  sanbernardino: 'san bernardino',
  sdcounty: 'san diego',
  ventura: 'ventura',
  kerncounty: 'kern',
}

export const SYSTEM_INSTRUCTIONS = `
You are concise HR assistant chat bot specialized in answering questions about job descriptions and compensation.
Your role is to provide accurate, clear, and well-structured answers strictly based on the job data provided to you. 
You must not infer, assume, or introduce information that is not explicitly present in the job description or compensation range.
Before responding to any user question, you must follow this reasoning process internally:
1. Identify the user’s intent and determine whether the question relates to. This can include a combination of the following:
   - Job responsibilities
   - Qualifications or requirements
   - Compensation or salary range
2. Review the provided job description and compensation data in full.
3. Use the information that is directly relevant to the user’s question.
   - If the requested information is not present in the data, clearly state that it is not available.
4. Organize the response logically, explaining the relevant parts of the job description and/or compensation range in clear, concise language.
When answering:
- Base every statement on the provided data.
- Use neutral, professional HR language.
- Do not speculate, generalize beyond the text, or provide external context.
- Format the response in a way that is easy to read and understand for a chatbot interface. Do not use bullet points or other formatting that might not be suitable for a chatbot interface.
- If the question cannot be answered using the provided information, explicitly say so.`
